{"name": "test_login[login_username_error]", "status": "passed", "attachments": [{"name": "log", "source": "5ddf87e3-5c63-4c8d-b312-7d6b5a2e1525-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'case': 'login_username_error', 'username': 18538231110, 'password': 'Gold77899', 'expected': '用户账户或密码错误'}"}], "start": 1756038581876, "stop": 1756038585994, "uuid": "9356b07c-b9e7-4f03-8b5d-ae0e68fd15c2", "historyId": "3ca944dea214f69b3bc91f5301606c9c", "testCaseId": "c54ba4c514553f220eeed2f7e798b554", "fullName": "testcase.test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户登录"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "li"}, {"name": "thread", "value": "8652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "titlePath": ["testcase", "test_login.py", "TestLogin"]}