{"name": "test_login[login_password_error]", "status": "passed", "attachments": [{"name": "log", "source": "59049ec3-a4bb-4525-98a4-6410a1d0350b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'case': 'login_password_error', 'username': 18538231111, 'password': 'Gold7789', 'expected': '密码错误'}"}], "start": 1756525582318, "stop": 1756525587061, "uuid": "cb726d05-59c2-4d5a-8ab1-658997c90d0e", "historyId": "0cbb37dbacea741fda169ac537e8da69", "testCaseId": "c54ba4c514553f220eeed2f7e798b554", "fullName": "testcase.test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "用户登录"}, {"name": "feature", "value": "用户登录"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "li"}, {"name": "thread", "value": "10064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}], "titlePath": ["testcase", "test_login.py", "TestLogin"]}